import pool from "@/lib/db";

const DOCS_URL = process.env.META_WHATSAPP_PRICING_DOCS_URL || "https://business.whatsapp.com/products/platform-pricing";

type RateRow = { currency:string; marketCode:string; countryCode:string|null; marketName:string; category:string; rate:number|null; effectiveFrom:string|null };
type TierRow = RateRow & { tierFrom:number; tierTo:number|null; discountPercent:number|null };

function norm(v:string){return String(v||"").trim().toLowerCase().replace(/[\s_–—-]+/g," ");}
function num(v:string|undefined){if(!v)return null;const n=Number(v.replace(/,/g,"").replace(/%/g,"").trim());return Number.isFinite(n)?n:null;}
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],n=text[i+1];if(ch==='"'&&quoted&&n==='"'){cell+='"';i++;continue}if(ch==='"'){quoted=!quoted;continue}if(!quoted&&ch===','){row.push(cell);cell="";continue}if(!quoted&&(ch==="\n"||ch==="\r")){if(ch==="\r"&&n==="\n")i++;row.push(cell);cell="";if(row.some(v=>v.trim()))rows.push(row);row=[];continue}cell+=ch}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;}
function effectiveDate(text:string){const m=text.match(/effective\s+([A-Za-z]+\s+\d{1,2},\s+\d{4})/i);if(!m)return null;const d=new Date(m[1]);return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10);}
function marketCode(name:string){const k=norm(name);const m:Record<string,string>={india:"IN",argentina:"AR",brazil:"BR",chile:"CL",colombia:"CO",egypt:"EG",france:"FR",germany:"DE","hong kong":"HK",hungary:"HU",indonesia:"ID",israel:"IL",italy:"IT",malaysia:"MY",mexico:"MX",netherlands:"NL",nigeria:"NG",pakistan:"PK",peru:"PE",russia:"RU","saudi arabia":"SA","south africa":"ZA",spain:"ES",turkey:"TR","united arab emirates":"AE","united kingdom":"GB","north america":"NA","rest of africa":"ROA","rest of asia pacific":"ROAP","rest of central and eastern europe":"ROCEE","rest of latin america":"ROLA","rest of middle east":"ROME","rest of western europe":"ROWE"};return m[k]||k.toUpperCase().replace(/[^A-Z0-9]+/g,"_");}
function headerIndex(rows:string[][]){return rows.findIndex(r=>{const h=r.map(norm).join("|");return h.includes("market")&&h.includes("currency");});}
function parseRates(text:string,currency:string):RateRow[]{const rows=parseCsv(text),hi=headerIndex(rows);if(hi<0)throw new Error("Meta rate CSV header not found.");const ef=effectiveDate(text),out:RateRow[]=[];const cats=["MARKETING","UTILITY","AUTHENTICATION","AUTHENTICATION_INTERNATIONAL","SERVICE"];for(const row of rows.slice(hi+1)){const market=(row[0]||"").trim();if(!market||norm(market)==="market")continue;const code=marketCode(market);cats.forEach((c,i)=>{if(row[i+2]!==undefined)out.push({currency,marketCode:code,countryCode:code.length===2?code:null,marketName:market,category:c,rate:num(row[i+2]),effectiveFrom:ef});});}return out;}
function parseTiers(text:string,currency:string):TierRow[]{const rows=parseCsv(text),hi=headerIndex(rows);if(hi<0)throw new Error("Meta volume-tier CSV header not found.");const ef=effectiveDate(text),out:TierRow[]=[];const groups=[["UTILITY",0],["AUTHENTICATION",5],["AUTHENTICATION_INTERNATIONAL",10]] as const;for(const row of rows.slice(hi+1)){const market=(row[0]||"").trim();if(!market||norm(market)==="market")continue;const code=marketCode(market),v=row.slice(2);for(const [cat,o] of groups){const from=num(v[o]),rate=num(v[o+3]);const raw=(v[o+1]||"").trim();const to=!raw||/^(--|n\/a)$/i.test(raw)?null:num(raw);const discount=num(v[o+4]);if(from===null||rate===null)continue;out.push({currency,marketCode:code,countryCode:code.length===2?code:null,marketName:market,category:cat,tierFrom:from,tierTo:to,rate,discountPercent:discount,effectiveFrom:ef});}}return out;}
async function download(url:string){const r=await fetch(url,{cache:"no-store",headers:{"user-agent":"Dispezo Meta pricing sync/1.0","accept":"text/csv,text/plain,*/*"}});if(!r.ok)throw new Error(\`Meta pricing download failed (\${r.status})\`);return r.text();}
async function sources(currency:string){const ratesUrl=process.env[\`META_WHATSAPP_\${currency}_RATES_CSV_URL\`],tiersUrl=process.env[\`META_WHATSAPP_\${currency}_VOLUME_TIERS_CSV_URL\`];if(!ratesUrl||!tiersUrl)throw new Error(\`Set META_WHATSAPP_\${currency}_RATES_CSV_URL and META_WHATSAPP_\${currency}_VOLUME_TIERS_CSV_URL to Meta's current official CSV download URLs.\`);return {ratesUrl,tiersUrl,ratesText:await download(ratesUrl),tiersText:await download(tiersUrl)};}
export async function syncMetaPricing(currency="INR"){const s=await sources(currency),rates=parseRates(s.ratesText,currency),tiers=parseTiers(s.tiersText,currency);const inRates=rates.filter(r=>r.marketCode==="IN");if(!inRates.some(r=>r.category==="MARKETING"&&r.rate!==null)||!inRates.some(r=>r.category==="UTILITY"&&r.rate!==null))throw new Error("Meta rate CSV validation failed for India.");if(!tiers.some(t=>t.marketCode==="IN"&&t.category==="UTILITY"))throw new Error("Meta volume-tier CSV validation failed for India.");const c=await pool.connect();try{await c.query("BEGIN");await c.query("SELECT pg_advisory_xact_lock(hashtext($1))",[\`meta-pricing-\${currency}\`]);await c.query("DELETE FROM whatsapp_volume_tiers WHERE currency=$1",[currency]);await c.query("DELETE FROM whatsapp_rate_cards WHERE currency=$1",[currency]);for(const r of rates)await c.query(\`INSERT INTO whatsapp_rate_cards(currency,market_code,country_code,market_name,category,rate,effective_from,source_url,synced_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,NOW())\`,[r.currency,r.marketCode,r.countryCode,r.marketName,r.category,r.rate,r.effectiveFrom,s.ratesUrl]);for(const t of tiers)await c.query(\`INSERT INTO whatsapp_volume_tiers(currency,market_code,country_code,market_name,category,tier_from,tier_to,rate,discount_percent,effective_from,source_url,synced_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NOW())\`,[t.currency,t.marketCode,t.countryCode,t.marketName,t.category,t.tierFrom,t.tierTo,t.rate,t.discountPercent,t.effectiveFrom,s.tiersUrl]);const ef=rates.find(r=>r.effectiveFrom)?.effectiveFrom||null;await c.query(\`INSERT INTO meta_pricing_sync_state(currency,last_successful_sync_at,last_effective_from,rates_source_url,tiers_source_url,last_error,updated_at) VALUES($1,NOW(),$2,$3,$4,NULL,NOW()) ON CONFLICT(currency) DO UPDATE SET last_successful_sync_at=NOW(),last_effective_from=EXCLUDED.last_effective_from,rates_source_url=EXCLUDED.rates_source_url,tiers_source_url=EXCLUDED.tiers_source_url,last_error=NULL,updated_at=NOW()\`,[currency,ef,s.ratesUrl,s.tiersUrl]);await c.query("COMMIT");return {currency,rates:rates.length,tiers:tiers.length,effectiveFrom:ef};}catch(e){await c.query("ROLLBACK").catch(()=>undefined);await pool.query(\`UPDATE meta_pricing_sync_state SET last_error=$2,updated_at=NOW() WHERE currency=$1\`,[currency,String(e).slice(0,2000)]).catch(()=>undefined);throw e;}finally{c.release();}}
export async function maybeSyncMetaPricing(currency="INR"){const r=await pool.query(\`SELECT last_successful_sync_at FROM meta_pricing_sync_state WHERE currency=$1 LIMIT 1\`,[currency]);const last=r.rows[0]?.last_successful_sync_at?new Date(r.rows[0].last_successful_sync_at):null;if(last&&Date.now()-last.getTime()<86400000)return {skipped:true};try{return await syncMetaPricing(currency);}catch(e){console.error("Meta pricing sync failed; keeping last successful rates:",e);return {failed:true};}}
export async function getMetaPricingSnapshot(currency="INR",marketCode="IN"){const [rates,tiers,sync]=await Promise.all([pool.query(\`SELECT category,rate,effective_from AS "effectiveFrom" FROM whatsapp_rate_cards WHERE currency=$1 AND market_code=$2 ORDER BY category\`,[currency,marketCode]),pool.query(\`SELECT category,tier_from AS "tierFrom",tier_to AS "tierTo",rate,discount_percent AS "discountPercent" FROM whatsapp_volume_tiers WHERE currency=$1 AND market_code=$2 ORDER BY category,tier_from\`,[currency,marketCode]),pool.query(\`SELECT last_successful_sync_at AS "lastSuccessfulSyncAt",last_effective_from AS "effectiveFrom",last_error AS "lastError" FROM meta_pricing_sync_state WHERE currency=$1 LIMIT 1\`,[currency])]);return {currency,marketCode,rates:rates.rows,tiers:tiers.rows,sync:sync.rows[0]||null};}
export async function getMetaRate(categoryName:string,volumeMessages=0,currency="INR",marketCode="IN"){const cat=categoryName.toUpperCase();if(volumeMessages>0&&["UTILITY","AUTHENTICATION","AUTHENTICATION_INTERNATIONAL"].includes(cat)){const t=await pool.query(\`SELECT rate FROM whatsapp_volume_tiers WHERE currency=$1 AND market_code=$2 AND category=$3 AND tier_from <= $4 AND (tier_to IS NULL OR tier_to >= $4) ORDER BY tier_from DESC LIMIT 1\`,[currency,marketCode,cat,volumeMessages]);if(t.rows[0]?.rate!=null)return Number(t.rows[0].rate);}const r=await pool.query(\`SELECT rate FROM whatsapp_rate_cards WHERE currency=$1 AND market_code=$2 AND category=$3 LIMIT 1\`,[currency,marketCode,cat]);return r.rows[0]?.rate==null?0:Number(r.rows[0].rate);}
